### ISSUE TITLE
Get "SyntaxError"

### ISSUE THREAD

**Issue by yutchor** [mjkaufer/Messer#40] opened 2017-11-28 08:17 UTC
> frostydog@Lenovopad:~$ messer ./Documents/messer/config.json 
> undefined:1
> undefined
> ^
> 
> SyntaxError: Unexpected token u in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/messer/src/helpers.js:50:39)
>     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)

>  frostydog@Lenovopad:$ node -v 
>  v9.2.0
>  frostydog@Lenovopad:$ npm -v
>  5.5.1

**Comment by johnwarmour** [comment] 2017-11-28 14:43
I think this is a duplicate of #39

**Comment by yutchor** [comment] 2017-11-29 04:20
@johnwarmour I am so sorry, Should I close this?

**Comment by johnwarmour** [comment] 2017-11-29 04:59
Haha, no need to be sorry, just a bit of bookkeeping. I’d say probably close this issue and just append any additional details you may have to #39.

**Closed** 2017-11-29 09:02 UTC
