### ISSUE TITLE
Doesn't work with two-factor authentication

### ISSUE THREAD

**Issue by DobaKung** [mjkaufer/Messer#20] opened 2016-12-25 16:55 UTC
![screen shot 2559-12-25 at 11 55 21 pm](https://cloud.githubusercontent.com/assets/3814520/21472131/a27a4c68-cafd-11e6-839f-9ccfedd6d9ea.png)

**Comment by tomquirk** [comment] 2016-12-26 20:42
Hey @DobaKung, as discussed in #16, the support in the API is there, just not implemented in Messer as of yet.

**Comment by tomquirk** [comment] 2017-03-16 03:11
Closing, duplicate of #16

**Closed by tomquirk** 2017-03-16 03:11 UTC
Labels: duplicate
