### ISSUE TITLE
Send message out of terminal without open messer first

### ISSUE THREAD

**Issue by Apop85** [mjkaufer/Messer#61] opened 2018-05-16 15:14 UTC
Hi there. 
I would like to create a script that automatically sends a message without me having to run messer first. Is it already possible to do this in the current version of messer? I was thinking of something like: `messer message "reciever" Hello World!` or similar. This command should then open messer, send the message and then close messer again. 

Greetings Apop

**Comment by tomquirk** [comment] 2018-06-03 02:49
Thanks for the suggestion @Apop85 , I would call it a duplicate of #58  though, I hope you agree

**Closed by tomquirk** 2018-06-03 02:49 UTC
