### ISSUE TITLE
TypeError: Cannot read property 'fullName' of undefined when get message send from others

### ISSUE THREAD

**Issue by Aries0d0f** [mjkaufer/Messer#59] opened 2018-04-30 07:33 UTC
When I got message send from others and it shows error message such like
```
TypeError: Cannot read property 'fullName' of undefined
    at getThreadById.then (/Users/aries/.nvm/versions/node/v9.8.0/lib/node_modules/messer/src/event-handlers.js:53:27)
    at <anonymous>
```

**Comment by lisaq** [comment] 2018-05-07 09:42
I'm also getting this error now. :/

**Comment by tomquirk** [comment] 2018-05-07 13:52
Hey @Aries0d0f @lisaq ,

Were you guys experiencing this for messages sent from people other than yourself? I managed to reproduce the error when I sent messages to myself, and have a fix ready to go (#60)

If yes, there's probably another issue related to the API we use (facebook-chat-api), and it looks like they are [working on a fix](https://github.com/Schmavery/facebook-chat-api/pull/572). I will keep an eye on this!

If you guys could also let us know if the messages failing were from friends (and if so, are they friends you frequently message) or not, that would be much appreciated!

**Comment by lisaq** [comment] 2018-05-07 15:38
I haven't tried to send a message to myself, actually. I get the message when I try to send messages to other people, or try to grab the history. I didn't happen to get any messages from anyone this morning to test what happens in that case.

**Comment by Aries0d0f** [comment] 2018-05-07 16:08
I restart it and it works fine now, but still broken sometimes; restart again and its work... probably facebook-chat-api's issues.

**Comment by tomquirk** [comment] 2018-05-07 21:52
Thanks guys. In light of the recent updates to facebook-chat-api (spanning back a couple of months now) it's probably worth us rethinking a few parts of Messer, particularly how we cache/store friends/threads locally. I'm guessing such work would solve a lot of these issues and improve maintainability. I'll keep this ticket open as a reminder to myself!

**Comment by bsansouci** [comment] 2018-05-22 00:37
Does this still happen now that we've merged https://github.com/Schmavery/facebook-chat-api/pull/572 ?

**Comment by tomquirk** [comment] 2018-05-22 01:14
yoo, nice. I'll have to check. Thanks for following up @bsansouci ❤️

**Closed** 2018-06-01 13:28 UTC
Labels: bug
